use_frameworks!

platform :ios, '9.0'

target 'XFSegmentView_Example' do
  pod 'XFSegmentView', :path => '../'

  target 'XFSegmentView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
